### PR TITLE
Improve build logic and inline svg

### PR DESCRIPTION
**Pull request by 8633brown**
a tidier version of #619 

improve the build config and get inline svg loader working.

also remove some of the unused dependencies.

### CODE REVIEW

**Comment by paulrosen** [comment]
I'm testing it now - it occurred to me that I'm not sure exactly what browsers are being targeted. I wonder if there should be a browser list?

**Comment by 8633brown** [comment]
I remember implementing Babel with corejs and setting it up with a browserlist. 

I can look into it again I think I remember it really increasing the transpiled size. So it never got merged. 

It would mean a lot of the old browser support functionality could be removed. And I believe it would be more reliable for older browsers but it does add a good size to the output files. 

One other thing about the SVG is if a client is importing those synth files directly, if they don't bundle it with webpack or an equivalent bundler with an SVG loader it will fail error on the SVG files I believe. 

I've not tested that but I think it would be a breaking change. I think that might be why it was originally commented out?

**Comment by paulrosen** [comment]
I think that might be it - I'll have to experiment with using it in various node modules. I don't want make someone have to change their webpack config to use the library.

**Comment by 8633brown** [comment]
Yeah absolutely. I'm sure it's something along those lines as to why it
wasn't used. I think the way round it was to use package.json `main` and
`module` sections to ensure npm used the transpiled code instead.

**Comment by 8633brown** [comment]
Just done a little more reading and [webpack](https://webpack.js.org/guides/author-libraries/#final-steps) shows their library example having pkg.main pointing to the generated code. 
So `pkg.main` would become `dist/abc-basic.js`

Changing this shouldn't make any difference to a user. But it makes a huge difference for the library as the source code can then be written in any format without affecting the user. I.e typescript, es6 or inline SVG.

Also if Babel was setup with the .browserlist setting pkg.main to the right location is the only way a user will get the benefits.

**Comment by paulrosen** [comment]
That sounds perfect, as long as there is a source map - it is also a requirement that someone including the library in a node environment be able to debug.

And high on my list is adding TypeScript - and this is a prerequisite for that. Thanks!

I hope to accept this PR this weekend.

**Comment by 8633brown** [comment]
I fixed the tests for testing in the browser. I removed Tarp as i dont think it agrees with inline SVG and we dont need it if we test against the compiled code. Which to me makes more sense as most users are going to be using the compiled code and if Typescript is ever used it needs to be compiled to test too does it not?

It might be a good idea to use a webpack watcher to compile as soon as theres a change? instead of relying on Tarp?

**Comment by paulrosen** [comment]
I tried `--watch` and it works reasonably well with the tests, but there is a big delay in minimizing which slows down development. Using watch on the non-minimized build is fast enough.

Perhaps I can just have `all.html` use the minimized version since that's all I need for cross-browser support, and I generally develop using the other test files.

**Comment by paulrosen** [comment]
I'm not sure what to do about midi.js. Perhaps it's time to stop supporting it since it is a pain.

**Comment by paulrosen** [comment]
I think `fix-versions` is no longer needed except for the `version.js` file. That seems like something that could be gotten from package.json instead, then we could get rid of that build step.

**Comment by paulrosen** [comment]
If we point users to unpkg we can get rid of the `/bin` folder altogether.

**Comment by 8633brown** [comment]
Ive not looked too much into the watch setup yet.
And the main reason i added midi.js to the dev deps is just to fix the build process. If you were to `git clone` `npm i` `npm run build` the build would fail looking for the midi dependencies to complete that part of the build process. If you wanted to stop supporting it thats your call.
Yeah i was actually having some small issues with `fix-versions` as it was writing the webpack file while i was editing and testing the build so vim was complaining as the file had been overwritten with no changes. I''ve not checked to really see where else the version is used. I can look into it though.

Im not sure what you mean by pointing users to unpkg? do you mean the `pkg.main` setting? Or do you just mean in general if anybody were to need an older version.

IMO if a user needs an older version the best way would be `npm i abcjs@[version]` but i suppose this requires a user to have node and npm with a bit of a build process setup.

**Comment by paulrosen** [comment]
To get it to watch all you have to do is add ` --watch` to the end of one of the build commands. It works great.

**Comment by 8633brown** [comment]
see #629 and #630

**Pull request closed without merging**
