### PR TITLE
Added option in abcjsParams for %%freegchord. This adds a new multilineVar which is a boolean (0/1).

### PR DESCRIPTION
**Pull request by ryan-frankel**
Effectively changed files:
package.json (bump to 5.9.2? I wasn't sure if you wanted me to do anything re:version)
src/parse/abc_parse.js
src/parse/abc_parse_directive.js

The freegchord option is set in the adbjsParams.format object...see below:

```
function initEditor() {
    new ABCJS.Editor("abc", { paper_id: "paper",
      generate_midi : false,
      generate_warnings : true,
      warnings_id : "warnings",
      abcjsParams: {
        responsive: "resize",
        add_classes: true,
        format : {
           freegchord  : 1,
            gchordfont : "Caveat Brush 14"
        }                                                                                                                                                                                }
    });
  }
```

### CODE REVIEW

**Comment by ryan-frankel** [comment]
Hey Paul,

Here is my shot at implementing freegchord.  Let me know if I missed the mark. I'm happy to make any changes. I did my best to follow your format/style.  But, I don't know the code base well lol.

**Comment by paulrosen** [comment]
Ok, I glanced at the changes but didn't run them. I see a few nits. I'll list them, and if you want to resubmit that would be great! I hope you'll continue contributing and you'll have more of an understanding of the architecture after this ---
1) in abc_parse, the if statement you put in skips the entire block, including setting the type to "default" and doing any transposition requested. The if statement should just be around the two lines.
2) The initialization of the multiline variables happens in abc_parse the function `multilineVars.reset()`. You had it where the fonts were being initialized.
3) You added support to `parseDirective.globalFormatting` which looks for the items passed in the options, but that won't pick up the statement `%%freegchord true`. That is done in some parallel code here: `parseDirective.addDirective`.

**Comment by ryan-frankel** [comment]
Hey Paul,

That makes sense. I wasn’t sure what you wanted as far as the version. I can take those changes out. 

*Sent from my phone. Sorry about short messages and any typos.

**Comment by ryan-frankel** [comment]
Thanks for the feedback. I will make those changes when I get a chance. This library has been incredibly useful for me. 

*Sent from my phone. Sorry about short messages and any typos.

**Comment by paulrosen** [comment]
I'm going to do another minor release this week - if I don't hear from you, I'll go ahead an implement this feature and put your name in the commit message.

**Comment by ryan-frankel** [comment]
Hey Paul. I will try to get to this tomorrow. Thanks for the heads up. 

*Sent from my phone. Sorry about short messages and any typos.

**Pull request closed without merging**
