### PR TITLE
fix to scale the click coords when paper is set to responsive

### PR DESCRIPTION
**Pull request by 8633brown**
This PR fixes an issue with selecting notes when the renderer is set to responsive I've only tested this on firefox.
It might be worth checking the svg element actually has these attributes before calculating the scaled values?

Basically what happens is when the renderer is set to responsive the mouse click coords are used which relate to the clicked elements X and Y. What should be used is the rendered svg viewport X and Y as the element and the viewport can be different widths and height.

Also just on a side note i didnt think it was worth posting an issue. I was wondering if youd be open to using something like [standard](https://standardjs.com/) or setting up eslint to format the code base somewhat? I know this can be very opinionated so thought id ask before looking into it?

### CODE REVIEW

**Comment by paulrosen** [comment]
This is working for me on firefox and safari, but not in chrome. Chrome reports the same value for `svg.height.baseVal.value` and `svg.clientHeight`. I called `renderAbc` with `{ responsive: "resize" }`.

**Comment by 8633brown** [comment]
should work now.

**Comment by paulrosen** [comment]
That now crashes in Firefox: svg.height.baseVal is undefined. I haven't studied this, here's a quick test I did on my computer:

  | scaleY | svg.height.baseVal.value | svg.clientHeight | svg.viewBox.baseVal.height
-- | -- | -- | -- | --
chrome not resp | 1 | 1628 | 1628 | 0
chrome resp | 1 | 2674 | 2674 | 1628
ff not resp | 1 | 1632 | 1632 |  undefined
ff resp | 0.44 | 1632 | 3676 |  undefined
safari not resp | 1 | 1625 | 1625 | 0
safari resp | 1 | 2457 | 2457 | 1625

The numbers are a bit different for each because I had different browser widths.

It looks like, perhaps, if svg.viewBox.baseVal.height exists and is not zero, use that, otherwise use svg.height.baseVal.value. I haven't tested edge, android, or ios yet.

**Comment by 8633brown** [comment]
tested with chrome and firefox responsive and unresponsive. seems good now. I cant test on safari.

**Pull request merged**
