### PR TITLE
enhance typescript types

### PR DESCRIPTION
**Pull request by jymen**
provide typedefs for visual and audio abcjs api

### CODE REVIEW

**Comment by paulrosen** [comment]
This looks great so far! Let me know if there is anything I can do to facilitate getting this out of "draft" status.

**Comment by jymen** [comment]
It's quite working right now ; but I will do complementary testing within my typescript code next days and hopefully some tiny enhancements/refinements and I will switch the status of the pull request to ready then

**Comment by jymen** [comment]
I have been testings the types declaration and it looks ok now for me ; if an example is needed I have a vue.js typescript component which looks like the full-synth although it may have some external tiny dependencies packages like logging ... just let me know

**Comment by paulrosen** [comment]
I would be interested in your typescript component - I'd like to make a typescript example.

**Comment by paulrosen** [comment]
Is there any reason why most of the "any" shouldn't be expanded? I think that will be for the next version of this.

**Comment by jymen** [comment]
For the 'any' : its only a matter of time to implement and stability of data structures used and for sure it can be expanded.
for the next version 

I got a question about transposition : Is there a way to get back the abc Source corresponding to the resulting  transposed visual score or not ? 
 
[abcjstypescript.zip](https://github.com/paulrosen/abcjs/files/6095657/abcjstypescript.zip)

Above zip contains 3 files :
- AbcScore.vue : this is the typescript vue showing abc scores and synth (quite similar to the full-synth example) ; there are some reference to some of my internal components (mainly used as input stuff or jogging)in it that can be easily cleanup (setting DEBUG to true shows the same display as full-synth )
- abcTest.ts : is just hosting the abc source 'Money Lost' used for testing
- abcSample.vue : is an example of calling AbcScore.vue component

**Comment by paulrosen** [comment]
Thanks so much. I got it working in a Vue 3/typescript project. I'll continue to refine the types as I go along.

**Pull request merged**
