### PR TITLE
Note load race fix

### PR DESCRIPTION
**Pull request by foxbunny**
This fix addresses the issue with race conditions when multiple
instances attempt to load the same note. One instance will
overwrite the resolved AudioBuffer from another instance with the
'pending' string. This fix addresses this by setting an instance
of a Promise instead of strings that represent the status, and
modifies putNote() so that it makes no assumptions about the
status, and instead simply resolves the promise to obtain the
buffer.

An example page is added that provides a demo for dynamic 
instrument (program) switching and toggling between two 
songs.

See #721

### CODE REVIEW

**Comment by paulrosen** [comment]
I tried your demo and I'm still getting a number of "Didn't load note acoustic_guitar_nylon E4 pending". Should that still be happening?

(Also, a little typo in your example. the handler should be `songPicker.onchange = function (event) {`)

**Comment by paulrosen** [comment]
Never mind - I didn't build. Your code seems to work.

**Comment by paulrosen** [comment]
I'm looking at the error cases. I'm hoping we can just report one error per failed note. And I don't want there to be a possibility of an unhandled rejection.

I'm experimenting with 1) remove the soundfont line so it uses my soundfont, 2) pick the polka, 3) switch to tuba.

There are a number of notes that are out of range for the tuba that won't load.

**Comment by foxbunny** [comment]
> (Also, a little typo in your example. the handler should be songPicker.onchange = function (event) {)

Thanks for checking. Will fix.

> I'm hoping we can just report one error per failed note.

Well, here's an idea. We could log the error in the `getNote()` rejection once, and the re-reject. Then `placeNote()` can catch it again but no log.

> And I don't want there to be a possibility of an unhandled rejection.

`placeNote()` will effectively swallow any and all rejections coming from the `noteBufferPromise`. Not sure if there are any other functions that use the cache.

**Comment by foxbunny** [comment]
> I'm experimenting with 1) remove the soundfont line so it uses my soundfont, 2) pick the polka, 3) switch to tuba.

Ok, I see the unhandled rejection. Thanks.

**Comment by foxbunny** [comment]
Updated the second commit:

- Removed the custom sound font
- Fixed issue with unhanded rejection by catching the rejection from `decodeAudioBuffer()`
- Added check for non-200 status so it does not even attempt to decode if nothing useful was returned
- Catch all errors in `getNote()`, log them and rethrow
- Simply suppress caught rejections in `placeNote()`

**Comment by paulrosen** [comment]
Looks good - one question, though: on line 175 there is `buffers = tunes.map(primeTune);`. Commenting it out gets rid of the audiocontext warning and doesn't seem to hurt anything. Is there a reason it is there?

**Comment by foxbunny** [comment]
> Looks good - one question, though: on line 175 there is buffers = tunes.map(primeTune);. Commenting it out gets rid of the audiocontext warning and doesn't seem to hurt anything. Is there a reason it is there?

I will check later. I might just be my misunderstanding of how things are done in ABCJS.

**Comment by foxbunny** [comment]
> hough: on line 175 there is buffers = tunes.map(primeTune);

I assume you mean L172. 

> Commenting it out gets rid of the audiocontext warning and doesn't seem to hurt anything.

Strange. For me it won't play the tunes if I just comment it out. I need to move the line to some event handler. The reason it's there is to pre-prime the tunes so that they can play immediately.

**Pull request merged**
