### PR TITLE
update webpack and build process

### PR DESCRIPTION
**Pull request by 8633brown**
This updates webpack and its related plugins/dependencies as well as removing some unued dependencies.

It also removes the need for a build-utils folder as the build process is somewhat more simplified now.

It also fixes the generation of the Licence files as it webpack didnt seem to want to import the original empty js file with the licence comment.

there are still some outdated dependenciess i think most of them are related to building the docs.

Ive also added an .editorconfig file to help standardize formatting rules.

### CODE REVIEW

**Comment by paulrosen** [comment]
I haven't tried this yet, but does
```
npm run docs:dev
npm run docs:build
```
work? The last time I tried to update webpack that was giving an error because VuePress doesn't support it yet. VuePress 2 is in alpha and will support it.

**Comment by paulrosen** [comment]
For the svg loader - that was an experiment to see if I could use .svg files and have them inlined in the js. I'd rather figure out why that didn't work than remove it, but I agree that it isn't used at the moment.

**Comment by paulrosen** [comment]
I don't want an editorconfig file at the moment.

**Comment by paulrosen** [comment]
Did you test
```
npm run build:analyze
```

**Comment by 8633brown** [comment]
ahh yeah good catch. I didnt think vuepress would be affected by webpack being updated.

So no 
```
npm run docs:dev
npm run docs:build
```
dont work

Yeah i noticed the commented out svg imports in some of the synth parts. The svg loader isn't needed anymore for webpack 5 but i didn't look too much into setting up the svg imports but i agree it would be better to do set them up with webpack.

Ill remove .editorconfig next time i get a chance to look at it. Any reason why?
I'll double check the analyze portion too when i get a chance.

**Comment by 8633brown** [comment]
I could downgrade webpack and still leave the simplified config. Should make upgrading to webpack 5 easier once vuepress v2 is released.
I just thought it was overkill having a

**Pull request closed without merging**
